# Generated by Django 3.2.8 on 2021-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('High', 'H'), ('Medium', 'M'), ('Low', 'L')], max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
