# Generated by Django 3.2.8 on 2021-10-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples_types', '0002_remove_apples_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apples',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
